### ISSUE TITLE
confuse  about the subtract operator.

### ISSUE THREAD

**Issue by sonygod** [samalexander/three-csg-ts#45]
**Describe the bug**

 CSG.subtract

**Minimal reproduction of issue**
Provide a [Stackblitz](https://stackblitz.com/) (or similar) that demonstrates the issue.

```js
import * as THREE from 'three';
import { CSG } from 'three-csg-ts';

// Make 2 meshes..
const plane= new THREE.Mesh(new THREE.PlaneGeometry(3, 3, 1, 1), new THREE.MeshNormalMaterial());
const box = new THREE.Mesh(new THREE.BoxGeometry(2, 2, 2), new THREE.MeshNormalMaterial());
);

// Make sure the .matrix of each mesh is current
box.updateMatrix();
plane.updateMatrix();

// Perform CSG operations
// The result is a THREE.Mesh that you can add to your scene...
const subRes = CSG.subtract(plane, box);
```

**Expected behavior**

I want only to get a plane with a hole instead of plane+hole+part of box.

**Screenshots**

![screenshot-localhost_2009-2022 01 19-15_37_34](https://user-images.githubusercontent.com/748320/150085549-5b4727e6-a615-426b-b602-a1b1f13ca974.png)

![screenshot-localhost_2009-2022 01 19-15_38_14](https://user-images.githubusercontent.com/748320/150085526-0cff2801-949d-41f8-aaad-fad9bed69556.png)

**Additional context**

**Comment by manthrax** [comment]
Short answer No.. The library doesn't work that way, and what you are calling a "plane" is not actually a true plane in the geometry sense, it's a coplanar triangulated quad. And a non volumetric object consisting of some co-planar polygons will extend off to infinity on the back side, which is why you see the result of your cube being chopped out of the plane. You can post process your geometry to remove the faces that you don't want though.

To get the effect that you want, I suggest taking the resulting geometry shown in your screenshot, and do your own processing on it to remove all the faces but the top faces. You can determine which of the faces is are top faces, by looking at the vertex normals for each face.
